name = "legal-tech-dashboard"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm ci && npx @cloudflare/next-on-pages@1"